server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      database: teams
      port: 27017
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true