server:
  port: 8080
  connection-timeout: 3000
  tomcat:
    max-connections: 5
spring:
  data:
    mongodb:
      host: localhost
      database: teams
      port: 27017
  jackson:
    write_dates_as_timestamps: true
    default-property-inclusion: non_null
    serialization:
      indent_output: true